name: Update Google Sheets from GitHub CSV

on:
  workflow_run:
    workflows: ["Format CSV File and Notify Telegram"]
    types:
      - completed
  workflow_dispatch:
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Google Sheet Upload Script
        run: python .github/Books_store_app/script_books_df_upload_to_gsheets.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          
      - name: Send Telegram Notification
        run: python .github/workflows/send_tg_notification.py "books_data_FORMATED.csv загружен в Google Sheets."
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
