name: Update Books Data File

on:
  schedule:
    - cron: '0 5 * * *'  # Запуск каждый день в 12:00 UTC (15:00 по Москве)
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Доступ для push

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas

      - name: Run update script
        run: python .github/Book_data_gen_script_git.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/books_database_main.csv
          git commit -m "🔄 Daily data update in books_database_main.csv $(date '+%Y-%m-%d')" || exit 0
          git push origin main 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Send Telegram Notification
        run: python .github/workflows/send_tg_notification.py "Обновление базы данныйх Books App успешно завершено! В файл books_database_main.csv добавлены данные за $(date '+%Y-%m-%d')."
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
